"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
import { Icon } from "@/shared/components/icon";
import type { CashierDashboard,CashierOrder,CashierSummary } from "../models/cashier";
import { statusLabel } from "../models/cashier";
import { cashierService } from "../services/cashier.service";
type View="dashboard"|"orders"|"payments"|"closing";
const q=(v:number)=>`Q ${v.toLocaleString("es-GT",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export function CashierWorkspace({view="dashboard"}:{view?:View}){const [dashboard,setDashboard]=useState<CashierDashboard|null>(null);const [orders,setOrders]=useState<CashierOrder[]>([]);const [payments,setPayments]=useState<any[]>([]);const [summary,setSummary]=useState<CashierSummary|null>(null);const [selected,setSelected]=useState<CashierOrder|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const load=useCallback(async()=>{setLoading(true);try{if(view==="dashboard")setDashboard(await cashierService.dashboard());if(view==="orders")setOrders((await cashierService.orders({limit:20})).items);if(view==="payments")setPayments((await cashierService.payments({limit:20})).items);if(view==="closing")setSummary(await cashierService.daily());}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[view]);useEffect(()=>{void load()},[load]);if(loading)return <div className="stitch-card p-10 text-center text-slate-500">Cargando caja...</div>;return <div className="mx-auto max-w-[1440px] space-y-5">{error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-800">{error}</p>}{view==="dashboard"&&dashboard&&<Dashboard data={dashboard}/>} {view==="orders"&&<Orders items={orders} onPay={setSelected}/>} {view==="payments"&&<Payments items={payments}/>} {view==="closing"&&summary&&<Closing data={summary}/>} {selected&&<PayModal order={selected} onClose={()=>setSelected(null)} onSaved={()=>{setSelected(null);void load()}}/>}</div>}
function Dashboard({data}:{data:CashierDashboard}){return <><header><p className="text-sm font-medium text-blue-700">Caja</p><h2 className="text-[28px] font-bold">Resumen de hoy</h2><p className="text-sm text-slate-600">Cobros y saldos con datos reales.</p></header><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric l="Cobrado hoy" v={q(data.totalAmount)}/><Metric l="Pagos registrados" v={data.paymentCount}/><Metric l="Órdenes con saldo" v={data.pendingOrders}/><Metric l="Efectivo" v={q(data.cashAmount)}/><Metric l="Transferencias" v={q(data.transferAmount)}/><Metric l="Otros métodos" v={q(data.otherAmount)}/></div><section className="stitch-card overflow-hidden"><h3 className="border-b p-4 font-bold">Últimos pagos</h3><PaymentRows items={data.recentPayments}/></section></>}
function Orders({items,onPay}:{items:CashierOrder[];onPay:(o:CashierOrder)=>void}){return <><header><h2 className="text-[28px] font-bold">Cobros / Órdenes</h2><p className="text-sm text-slate-600">Consulta el saldo antes de registrar un pago.</p></header><section className="stitch-card overflow-x-auto"><table className="stitch-table"><thead><tr><th>Orden</th><th>Cliente</th><th>Total</th><th>Pagado</th><th>Saldo</th><th>Financiero</th><th>Operativo</th><th/></tr></thead><tbody>{items.map(o=><tr key={o.workOrderId}><td className="font-bold text-blue-700">{o.workOrderCode}</td><td>{o.clientName}</td><td>{o.totalAmount===null?"Sin monto":q(o.totalAmount)}</td><td>{q(o.totalPaid)}</td><td>{o.balance===null?"—":q(o.balance)}</td><td><span className="rounded-full bg-blue-100 px-2 py-1 text-xs">{statusLabel[o.financialStatus]}</span></td><td>{o.operationalStatus}</td><td><button disabled={!o.balance||o.balance<=0} onClick={()=>onPay(o)} className="stitch-button stitch-button-primary">Cobrar</button></td></tr>)}{!items.length&&<tr><td colSpan={8} className="p-8 text-center text-slate-500">No hay órdenes.</td></tr>}</tbody></table></section></>}
function Payments({items}:{items:any[]}){return <><header><h2 className="text-[28px] font-bold">Historial de pagos</h2></header><section className="stitch-card overflow-hidden"><PaymentRows items={items}/></section></>}
function PaymentRows({items}:{items:any[]}){return <div className="overflow-x-auto"><table className="stitch-table"><thead><tr><th>Fecha</th><th>Orden</th><th>Cliente</th><th>Método</th><th>Referencia</th><th>Cajero</th><th>Monto</th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td>{new Intl.DateTimeFormat("es-GT",{dateStyle:"short",timeStyle:"short"}).format(new Date(p.createdAt))}</td><td>{p.workOrderCode}</td><td>{p.clientName}</td><td>{p.method}</td><td>{p.reference??"—"}</td><td>{p.receivedBy??"—"}</td><td className="font-bold text-emerald-700">{q(p.amount)}</td></tr>)}{!items.length&&<tr><td colSpan={7} className="p-8 text-center text-slate-500">Sin pagos para mostrar.</td></tr>}</tbody></table></div>}
function Closing({data}:{data:CashierSummary}){return <><header><h2 className="text-[28px] font-bold">Cierre de caja</h2><p className="text-sm text-slate-600">Resumen dinámico del {data.businessDate}; no se almacenan totales derivados.</p></header><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric l="Pagos" v={data.paymentCount}/><Metric l="Total cobrado" v={q(data.totalAmount)}/><Metric l="Efectivo" v={q(data.cashAmount)}/><Metric l="Transferencias" v={q(data.transferAmount)}/><Metric l="Otros" v={q(data.otherAmount)}/><Metric l="Órdenes cobradas" v={data.paidOrders}/><Metric l="Pendientes" v={data.pendingOrders}/></div></>}
function Metric({l,v}:{l:string;v:string|number|CashierOrder[]}){return <div className="stitch-card p-4"><p className="text-sm text-slate-500">{l}</p><strong className="mt-2 block text-2xl">{Array.isArray(v)?v.length:v}</strong></div>}
function PayModal({order,onClose,onSaved}:{order:CashierOrder;onClose:()=>void;onSaved:()=>void}){const [amount,setAmount]=useState("");const [method,setMethod]=useState("Efectivo");const [reference,setReference]=useState("");const [notes,setNotes]=useState("");const [error,setError]=useState("");const [saving,setSaving]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();const value=Number(amount);if(!Number.isFinite(value)||value<=0){setError("Ingresa un monto válido.");return}try{setSaving(true);await cashierService.create({workOrderId:order.workOrderId,amount:value,method,reference:reference||null,notes:notes||null});onSaved()}catch(x){setError((x as Error).message)}finally{setSaving(false)}};return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={e=>void submit(e)} className="stitch-card w-full max-w-lg p-6"><h2 className="text-xl font-bold">Registrar pago</h2><div className="my-4 rounded bg-slate-50 p-3 text-sm"><strong>{order.workOrderCode} · {order.clientName}</strong><p>Total: {order.totalAmount===null?"—":q(order.totalAmount)} · Pagado: {q(order.totalPaid)} · Saldo: {q(order.balance??0)}</p></div><div className="space-y-3"><input required type="number" min="0.01" max={order.balance??undefined} step="0.01" className="stitch-input" placeholder="Monto en quetzales" value={amount} onChange={e=>setAmount(e.target.value)}/><select className="stitch-input" value={method} onChange={e=>setMethod(e.target.value)}><option>Efectivo</option><option>Transferencia</option><option>Tarjeta</option><option>Otro</option></select>{method==="Transferencia"&&<input required className="stitch-input" placeholder="Referencia bancaria" value={reference} onChange={e=>setReference(e.target.value)}/>}<textarea className="stitch-input h-20 py-2" placeholder="Notas" value={notes} onChange={e=>setNotes(e.target.value)}/></div>{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button type="button" className="stitch-button stitch-button-secondary" onClick={onClose}>Cancelar</button><button disabled={saving} className="stitch-button stitch-button-primary">{saving?"Registrando...":"Confirmar pago"}</button></div></form></div>}
