"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import type { Payment, WorkOrder } from "@/shared/models/admin";
import { apiRequest } from "@/shared/services/api";
import { Icon } from "@/shared/components/icon";

const blank = { workOrderId: "", amount: "", method: "Efectivo", reference: "", notes: "" };
export function FinanceView() {
  const [payments, setPayments] = useState<Payment[]>([]); const [orders, setOrders] = useState<WorkOrder[]>([]); const [form, setForm] = useState(blank); const [adding, setAdding] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { try { const [paymentData, orderData] = await Promise.all([apiRequest<{ items: Payment[] }>("/api/admin/payments"), apiRequest<{ items: WorkOrder[] }>("/api/admin/work-orders?limit=100")]); setPayments(paymentData.items); setOrders(orderData.items); } catch (caught) { setError((caught as Error).message); } }, []);
  useEffect(() => { void load(); }, [load]);
  const submit = async (event: FormEvent) => { event.preventDefault(); try { await apiRequest("/api/admin/payments", { method: "POST", body: JSON.stringify({ ...form, amount: Number(form.amount) }) }); setForm(blank); setAdding(false); await load(); } catch (caught) { setError((caught as Error).message); } };
  const total = payments.reduce((sum, item) => sum + item.amount, 0); const set = (key: keyof typeof blank, value: string) => setForm({ ...form, [key]: value });
  return <div className="mx-auto max-w-[1440px]"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-[28px] font-bold">Finanzas</h2><p className="mt-1 text-slate-600">Registre ingresos asociados a una orden de trabajo.</p></div><button className="stitch-button stitch-button-primary" onClick={() => setAdding(true)}><Icon name="add" />Registrar pago</button></div>{error && <p role="alert" className="mb-4 rounded bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    <div className="mb-5 grid gap-4 sm:grid-cols-2"><div className="stitch-card p-5"><p className="text-sm text-slate-500">Ingresos registrados</p><strong className="mt-1 block text-3xl text-emerald-700">Q {total.toFixed(2)}</strong></div><div className="stitch-card p-5"><p className="text-sm text-slate-500">Movimientos</p><strong className="mt-1 block text-3xl">{payments.length}</strong></div></div>
    <section className="stitch-card overflow-hidden"><div className="overflow-x-auto"><table className="stitch-table"><thead><tr><th>Fecha</th><th>Orden</th><th>Cliente</th><th>Método</th><th>Referencia</th><th className="text-right">Monto</th></tr></thead><tbody>{payments.map((payment) => <tr key={payment.id}><td>{date(payment.createdAt)}</td><td className="font-medium text-blue-700">{payment.workOrderCode}</td><td>{payment.clientName}</td><td>{payment.method}</td><td>{payment.reference ?? "—"}</td><td className="text-right font-bold text-emerald-700">Q {payment.amount.toFixed(2)}</td></tr>)}{!payments.length && <tr><td colSpan={6} className="p-10 text-center text-slate-500">Aún no hay pagos registrados.</td></tr>}</tbody></table></div></section>
    {adding && <div className="fixed inset-0 z-30 flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={submit} className="stitch-card w-full max-w-lg p-6"><div className="flex justify-between"><h3 className="text-xl font-bold">Registrar pago</h3><button type="button" onClick={() => setAdding(false)}><Icon name="close" /></button></div><div className="mt-5 grid gap-4"><Field label="Orden de trabajo"><select required className="stitch-input" value={form.workOrderId} onChange={(e) => set("workOrderId", e.target.value)}><option value="">Seleccione una orden</option>{orders.map((order) => <option key={order.id} value={order.id}>{order.code} · {order.clientName}</option>)}</select></Field><Field label="Monto (Q)"><input required min="0.01" step="0.01" type="number" className="stitch-input" value={form.amount} onChange={(e) => set("amount", e.target.value)} /></Field><Field label="Método"><select className="stitch-input" value={form.method} onChange={(e) => set("method", e.target.value)}><option>Efectivo</option><option>Transferencia</option><option>Tarjeta</option><option>Cheque</option></select></Field><Field label="Referencia"><input className="stitch-input" value={form.reference} onChange={(e) => set("reference", e.target.value)} /></Field><Field label="Notas"><textarea className="stitch-input h-20 py-2" value={form.notes} onChange={(e) => set("notes", e.target.value)} /></Field></div><div className="mt-6 flex justify-end gap-2"><button type="button" className="stitch-button stitch-button-secondary" onClick={() => setAdding(false)}>Cancelar</button><button className="stitch-button stitch-button-primary">Guardar pago</button></div></form></div>}</div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm font-medium text-slate-700"><span className="mb-1.5 block">{label}</span>{children}</label>; }
const date = (value: string) => new Intl.DateTimeFormat("es-GT", { dateStyle: "short" }).format(new Date(value));
