"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import type { WorkOrder, WorkOrderEvent } from "@/shared/models/admin";
import { apiRequest } from "@/shared/services/api";
import { PriorityBadge } from "@/shared/components/priority-badge";
import { ProgressBar } from "@/shared/components/progress-bar";
import { StatusBadge } from "@/shared/components/status-badge";

export function OperationalOrderDetailView({ id }: { id: string }) {
  const [order, setOrder] = useState<WorkOrder | null>(null); const [events, setEvents] = useState<WorkOrderEvent[]>([]); const [error, setError] = useState(""); const [mode, setMode] = useState<"progress" | "complete" | null>(null); const [working, setWorking] = useState(false); const [today, setToday] = useState<Date | null>(null);
  const load = useCallback(async () => { try { const [detail, history] = await Promise.all([apiRequest<{ order: WorkOrder }>(`/api/operativo/orders/${id}`), apiRequest<{ items: WorkOrderEvent[] }>(`/api/operativo/orders/${id}/history`)]); setOrder(detail.order); setEvents(history.items); } catch (caught) { setError((caught as Error).message); } }, [id]); useEffect(() => { void load(); }, [load]);
  const start = async () => { if (!confirm("¿Deseas iniciar esta orden de trabajo?")) return; setWorking(true); try { await apiRequest(`/api/operativo/orders/${id}/start`, { method: "POST" }); await load(); } catch (caught) { setError((caught as Error).message); } finally { setWorking(false); } };
  const submit = async (payload: { progress?: number; observation: string }) => { setWorking(true); try { const endpoint = mode === "complete" ? `/api/operativo/orders/${id}/complete` : `/api/operativo/orders/${id}/progress`; await apiRequest(endpoint, { method: mode === "complete" ? "POST" : "PATCH", body: JSON.stringify(payload) }); setMode(null); await load(); } catch (caught) { setError((caught as Error).message); } finally { setWorking(false); } };
  useEffect(() => { setToday(new Date()); }, []);
  if (!order && !error) return <p className="text-slate-500">Cargando orden...</p>;
  if (!order) return <div><Link href="/operativo/ordenes" className="text-sm font-semibold text-blue-700">← Volver a mis órdenes</Link><p role="alert" className="mt-4 rounded bg-red-50 p-4 text-red-800">{error}</p></div>;
  const days = order.estimatedDate && today ? Math.ceil((new Date(order.estimatedDate).getTime() - today.getTime()) / 86400000) : null;
  return <div className="mx-auto max-w-[1280px]"><Link href="/operativo/ordenes" className="text-sm font-semibold text-blue-700">← Volver a mis órdenes</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-3xl font-bold">Orden {order.code}</h1><StatusBadge status={order.status} /><PriorityBadge priority={order.priority} /></div><p className="mt-2 text-slate-600">Información operativa de la reparación asignada.</p></div><div className="flex gap-2">{order.status === "PENDING" && <button disabled={working} className="stitch-button stitch-button-primary" onClick={() => void start()}>Iniciar trabajo</button>}{order.status === "IN_PROGRESS" && <><button className="stitch-button stitch-button-secondary" onClick={() => setMode("progress")}>Registrar avance</button><button className="stitch-button bg-emerald-600 text-white hover:bg-emerald-700" onClick={() => setMode("complete")}>Finalizar trabajo</button></>}</div></div>{error && <p role="alert" className="mt-4 rounded bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Estado actual" value={<StatusBadge status={order.status} />} /><Metric label="Avance general" value={<ProgressBar value={order.progress} />} /><Metric label="Fecha estimada" value={order.estimatedDate ? date(order.estimatedDate) : "No definida"} /><Metric label="Tiempo restante" value={days === null ? "Sin fecha" : days < 0 ? "Vencida" : `${days} días`} /></section>
    <div className="mt-6 grid gap-5 xl:grid-cols-[1.65fr_0.9fr]"><div className="space-y-5"><section className="stitch-card p-6"><div className="flex justify-between"><h2 className="text-lg font-bold">Datos del motor</h2><span className="text-xs text-slate-500">Solo lectura</span></div><dl className="mt-5 grid gap-4 sm:grid-cols-3"><Info label="Marca" value={order.engineBrand} /><Info label="Modelo" value={order.engineModel} /><Info label="Número de serie" value={order.engineSerial ?? "No registrado"} /></dl></section><section className="stitch-card p-6"><h2 className="text-lg font-bold">Trabajo solicitado</h2><Info label="Servicio" value={order.serviceType} /><p className="mt-4 text-sm text-slate-600">{order.description}</p><div className="mt-5 grid gap-3 border-t border-slate-200 pt-4 sm:grid-cols-2"><Info label="Cliente" value={order.clientName} /><Info label="Fecha de ingreso" value={date(order.createdAt)} /><Info label="Fecha estimada" value={order.estimatedDate ? date(order.estimatedDate) : "No definida"} /><Info label="Trabajador asignado" value={order.assignedWorker ?? "No asignado"} /></div></section><section className="stitch-card p-6"><h2 className="text-lg font-bold">Historial de avances</h2><div className="mt-5 space-y-4">{events.map((event) => <article key={event.id} className="border-l-2 border-blue-600 pl-4"><div className="flex flex-wrap justify-between gap-2"><strong>{eventLabel(event.eventType)}</strong><span className="text-xs text-slate-500">{dateTime(event.createdAt)}</span></div><p className="mt-1 text-sm text-slate-600">{event.message}</p>{event.progress !== null && <p className="mt-1 text-sm font-semibold text-blue-700">Avance: {event.progress}%</p>}</article>)}{!events.length && <p className="text-sm text-slate-500">Aún no hay actualizaciones registradas.</p>}</div></section></div><aside className="space-y-5"><section className="stitch-card p-5"><h2 className="font-bold">Progreso de la reparación</h2><p className="mt-4 text-3xl font-bold text-blue-700">{order.progress}%</p><div className="mt-3"><ProgressBar value={order.progress} /></div><p className="mt-4 text-sm text-slate-600">{order.status === "COMPLETED" ? "La reparación está finalizada y bloqueada para nuevos avances." : "Registra actualizaciones para mantener el progreso al día."}</p></section><section className="stitch-card p-5"><h2 className="font-bold">Notas de recepción</h2><p className="mt-3 text-sm text-slate-600">{order.intakeNotes ?? "No hay notas de recepción."}</p></section></aside></div>{mode && <OrderUpdateDialog order={order} mode={mode} saving={working} close={() => setMode(null)} submit={submit} />}</div>;
}
function OrderUpdateDialog({ order, mode, saving, close, submit }: { order: WorkOrder; mode: "progress" | "complete"; saving: boolean; close: () => void; submit: (payload: { progress?: number; observation: string }) => Promise<void> }) { const [progress, setProgress] = useState(String(order.progress)); const [observation, setObservation] = useState(""); const [error, setError] = useState(""); const save = async (event: FormEvent) => { event.preventDefault(); const next = Number(progress); if (mode === "progress" && (!Number.isInteger(next) || next < order.progress || next > 100)) return setError(`El avance debe estar entre ${order.progress}% y 100%.`); if (!observation.trim()) return setError("Escribe una observación para el historial."); await submit({ progress: mode === "progress" ? next : undefined, observation }); }; return <div className="fixed inset-0 z-30 flex items-center justify-center bg-slate-950/45 p-4"><form onSubmit={(e) => void save(e)} className="stitch-card w-full max-w-xl p-6"><h2 className="text-2xl font-bold">{mode === "progress" ? "Registrar avance" : "Finalizar reparación"}</h2><p className="mt-1 text-sm text-slate-600">{order.code} · {order.engineBrand} {order.engineModel}</p>{error && <p role="alert" className="mt-4 rounded bg-red-50 p-3 text-sm text-red-800">{error}</p>}{mode === "progress" && <label className="mt-5 block text-sm font-semibold">Porcentaje de avance<input type="number" min={order.progress} max="100" className="stitch-input mt-2" value={progress} onChange={(e) => setProgress(e.target.value)} /></label>}<label className="mt-5 block text-sm font-semibold">{mode === "complete" ? "Observación final" : "Observación"}<textarea className="stitch-input mt-2 h-28 py-2" value={observation} onChange={(e) => setObservation(e.target.value)} placeholder="Describe el trabajo realizado o el resultado de la reparación." /></label><div className="mt-6 flex justify-end gap-2"><button type="button" className="stitch-button stitch-button-secondary" onClick={close}>Cancelar</button><button disabled={saving} className={`stitch-button text-white ${mode === "complete" ? "bg-emerald-600 hover:bg-emerald-700" : "stitch-button-primary"}`}>{saving ? "Guardando..." : mode === "complete" ? "Finalizar reparación" : "Registrar avance"}</button></div></form></div>; }
function Metric({ label, value }: { label: string; value: React.ReactNode }) { return <section className="stitch-card p-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><div className="mt-3 font-semibold">{value}</div></section>; }
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 text-sm font-medium">{value}</dd></div>; }
const date = (value: string) => new Intl.DateTimeFormat("es-GT", { dateStyle: "short" }).format(new Date(value)); const dateTime = (value: string) => new Intl.DateTimeFormat("es-GT", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)); const eventLabel = (type: string) => ({ ORDER_ASSIGNED: "Orden asignada", WORK_STARTED: "Trabajo iniciado", PROGRESS_UPDATED: "Avance actualizado", WORK_COMPLETED: "Orden finalizada" }[type] ?? type);
