"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import type { OperationalDashboard } from "@/shared/models/admin";
import { apiRequest } from "@/shared/services/api";
import { PriorityBadge } from "@/shared/components/priority-badge";
import { ProgressBar } from "@/shared/components/progress-bar";
import { StatusBadge } from "@/shared/components/status-badge";

export function OperationalDashboardView() { const [data, setData] = useState<OperationalDashboard | null>(null); const [error, setError] = useState(""); useEffect(() => { void apiRequest<{ dashboard: OperationalDashboard }>("/api/operativo/dashboard").then((result) => setData(result.dashboard)).catch((caught: Error) => setError(caught.message)); }, []); return <div className="mx-auto max-w-[1280px]"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Inicio / Operativo</p><h1 className="mt-2 text-3xl font-bold">Mi trabajo</h1><p className="mt-1 text-slate-600">Consulta tu carga actual y las reparaciones que requieren atención.</p>{error && <p role="alert" className="mt-5 rounded bg-red-50 p-3 text-sm text-red-800">{error}</p>}<div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Órdenes asignadas" value={data?.total ?? "—"} /><Metric label="Pendientes de iniciar" value={data?.pending ?? "—"} tone="text-amber-700" /><Metric label="En proceso" value={data?.in_progress ?? "—"} tone="text-blue-700" /><Metric label="Finalizadas hoy" value={data?.completed_today ?? "—"} tone="text-emerald-700" /></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><Alert label="Urgentes" value={data?.urgent ?? 0} tone="border-red-200 bg-red-50 text-red-700" /><Alert label="Próximas a vencer" value={data?.due_soon ?? 0} tone="border-amber-200 bg-amber-50 text-amber-800" /><Alert label="Vencidas" value={data?.overdue ?? 0} tone="border-red-200 bg-red-50 text-red-700" /></div><section className="stitch-card mt-6 overflow-hidden"><div className="flex items-center justify-between p-5"><div><h2 className="font-bold">Próximas órdenes</h2><p className="mt-1 text-sm text-slate-500">Ordenadas por prioridad y fecha estimada.</p></div><Link href="/operativo/ordenes" className="text-sm font-semibold text-blue-700 hover:underline">Ver todas</Link></div><div className="overflow-x-auto"><table className="stitch-table"><thead><tr><th>Número</th><th>Motor</th><th>Estado</th><th>Avance</th><th>Prioridad</th><th></th></tr></thead><tbody>{data?.upcoming.map((order) => <tr key={order.id}><td className="font-semibold text-blue-700">{order.code}</td><td>{order.engineBrand} {order.engineModel}</td><td><StatusBadge status={order.status} /></td><td><ProgressBar value={order.progress} /></td><td><PriorityBadge priority={order.priority} /></td><td><Link className="text-sm font-semibold text-blue-700" href={`/operativo/ordenes/${order.id}`}>Abrir</Link></td></tr>)}{data && !data.upcoming.length && <tr><td colSpan={6} className="p-8 text-center text-slate-500">No tienes órdenes asignadas actualmente.</td></tr>}</tbody></table></div></section></div>; }
function Metric({ label, value, tone = "text-slate-900" }: { label: string; value: number | string; tone?: string }) { return <article className="stitch-card p-5"><p className="text-sm font-medium text-slate-600">{label}</p><strong className={`mt-2 block text-3xl ${tone}`}>{value}</strong></article>; }
function Alert({ label, value, tone }: { label: string; value: number; tone: string }) { return <div className={`rounded-lg border p-4 ${tone}`}><strong className="text-2xl">{value}</strong><span className="ml-2 text-sm font-semibold">{label}</span></div>; }
