"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import type { OperationalDashboard, Paginated, WorkOrder } from "@/shared/models/admin";
import { apiRequest } from "@/shared/services/api";
import { Icon } from "@/shared/components/icon";
import { PriorityBadge } from "@/shared/components/priority-badge";
import { ProgressBar } from "@/shared/components/progress-bar";
import { StatusBadge } from "@/shared/components/status-badge";

type Filters = { search: string; status: string; priority: string; date: string };
const empty: Filters = { search: "", status: "", priority: "", date: "" };
export function OperationalOrdersView() {
  const [filters, setFilters] = useState(empty); const [applied, setApplied] = useState(empty); const [view, setView] = useState<"list" | "cards">("list"); const [page, setPage] = useState(1); const [orders, setOrders] = useState<Paginated<WorkOrder> | null>(null); const [summary, setSummary] = useState<OperationalDashboard | null>(null); const [error, setError] = useState(""); const limit = 8;
  const load = useCallback(async () => { try { const query = new URLSearchParams({ page: String(page), limit: String(limit) }); Object.entries(applied).forEach(([key, value]) => { if (value) query.set(key, value); }); const [listed, dashboard] = await Promise.all([apiRequest<Paginated<WorkOrder>>(`/api/operativo/orders?${query}`), apiRequest<{ dashboard: OperationalDashboard }>("/api/operativo/dashboard")]); setOrders(listed); setSummary(dashboard.dashboard); } catch (caught) { setError((caught as Error).message); } }, [applied, page]);
  useEffect(() => { void load(); }, [load]); const set = (key: keyof Filters, value: string) => setFilters({ ...filters, [key]: value }); const apply = () => { setPage(1); setApplied(filters); }; const clear = () => { setFilters(empty); setApplied(empty); setPage(1); };
  const pages = Math.max(1, Math.ceil((orders?.total ?? 0) / limit));
  return <div className="mx-auto max-w-[1280px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Inicio / Mis órdenes asignadas</p><h1 className="mt-2 text-3xl font-bold">Mis órdenes asignadas</h1><p className="mt-1 text-slate-600">Consulta las reparaciones que tienes asignadas y registra su avance.</p></div><div className="flex gap-2"><button className="stitch-button stitch-button-secondary" onClick={() => void load()}><Icon name="history" />Actualizar</button><div className="flex rounded-lg border border-slate-200 bg-slate-100 p-1"><button className={`rounded px-3 text-sm font-semibold ${view === "list" ? "bg-white text-blue-700 shadow-sm" : "text-slate-600"}`} onClick={() => setView("list")}>Lista</button><button className={`rounded px-3 text-sm font-semibold ${view === "cards" ? "bg-white text-blue-700 shadow-sm" : "text-slate-600"}`} onClick={() => setView("cards")}>Tarjetas</button></div></div></div>{error && <p role="alert" className="mt-4 rounded bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Órdenes asignadas" value={summary?.total ?? "—"} /><Metric label="Pendientes de iniciar" value={summary?.pending ?? "—"} tone="text-amber-700" /><Metric label="En proceso" value={summary?.in_progress ?? "—"} tone="text-blue-700" /><Metric label="Finalizadas hoy" value={summary?.completed_today ?? "—"} tone="text-emerald-700" /></section>
    <section className="stitch-card mt-6 grid gap-3 p-5 md:grid-cols-[1.4fr_1fr_1fr_1fr_auto]"><label className="relative"><Icon name="search" className="absolute left-3 top-2.5 text-slate-500" /><input className="stitch-input stitch-input-with-icon" value={filters.search} onChange={(e) => set("search", e.target.value)} placeholder="Buscar por orden o motor" /></label><select className="stitch-input" value={filters.status} onChange={(e) => set("status", e.target.value)}><option value="">Estado: Todos</option><option value="PENDING">Pendiente</option><option value="IN_PROGRESS">En proceso</option><option value="COMPLETED">Finalizada</option></select><select className="stitch-input" value={filters.priority} onChange={(e) => set("priority", e.target.value)}><option value="">Prioridad: Todas</option><option value="NORMAL">Normal</option><option value="HIGH">Alta</option><option value="URGENT">Urgente</option></select><select className="stitch-input" value={filters.date} onChange={(e) => set("date", e.target.value)}><option value="">Fecha: Todas</option><option value="UPCOMING">Próximas 7 días</option><option value="OVERDUE">Vencidas</option></select><div className="flex gap-2"><button className="stitch-button stitch-button-primary" onClick={apply}>Aplicar</button><button className="stitch-button stitch-button-secondary" onClick={clear}>Limpiar</button></div></section>
    {view === "list" ? <OrderTable orders={orders?.items ?? []} /> : <OrderCards orders={orders?.items ?? []} />}
    {orders && <div className="mt-4 flex items-center justify-between text-sm text-slate-600"><span>Mostrando {orders.items.length} de {orders.total} órdenes</span><div className="flex gap-2"><button disabled={page === 1} className="stitch-button stitch-button-secondary disabled:opacity-50" onClick={() => setPage(page - 1)}>Anterior</button><span className="flex items-center px-2 font-semibold">{page} / {pages}</span><button disabled={page === pages} className="stitch-button stitch-button-secondary disabled:opacity-50" onClick={() => setPage(page + 1)}>Siguiente</button></div></div>}</div>;
}
function OrderTable({ orders }: { orders: WorkOrder[] }) { return <section className="stitch-card mt-6 overflow-x-auto"><table className="stitch-table"><thead><tr><th>Número</th><th>Motor</th><th>Servicio</th><th>Estado</th><th>Avance</th><th>Prioridad</th><th>Fecha estimada</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td><Link className="font-bold text-blue-700 hover:underline" href={`/operativo/ordenes/${order.id}`}>{order.code}</Link></td><td>{order.engineBrand}<br />{order.engineModel}</td><td>{order.serviceType}</td><td><StatusBadge status={order.status} /></td><td><ProgressBar value={order.progress} /></td><td><PriorityBadge priority={order.priority} /></td><td className={due(order) ? "font-semibold text-red-700" : ""}>{order.estimatedDate ? date(order.estimatedDate) : "Sin fecha"}{due(order) && <small className="mt-1 block">Vencida</small>}</td></tr>)}{!orders.length && <tr><td colSpan={7} className="p-10 text-center text-slate-500">No tienes órdenes asignadas actualmente.</td></tr>}</tbody></table></section>; }
function OrderCards({ orders }: { orders: WorkOrder[] }) { return <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{orders.map((order) => <Link className="stitch-card block p-5 transition hover:border-blue-300 hover:shadow-md" key={order.id} href={`/operativo/ordenes/${order.id}`}><div className="flex justify-between gap-3"><strong className="text-blue-700">{order.code}</strong><PriorityBadge priority={order.priority} /></div><h2 className="mt-3 font-bold">{order.engineBrand} {order.engineModel}</h2><p className="mt-1 text-sm text-slate-600">{order.serviceType}</p><div className="mt-4 flex items-center justify-between"><StatusBadge status={order.status} /><span className={`text-sm ${due(order) ? "font-semibold text-red-700" : "text-slate-500"}`}>{order.estimatedDate ? date(order.estimatedDate) : "Sin fecha"}</span></div><div className="mt-4"><ProgressBar value={order.progress} /></div></Link>)}{!orders.length && <p className="text-slate-500">No tienes órdenes asignadas actualmente.</p>}</section>; }
function Metric({ label, value, tone = "text-slate-900" }: { label: string; value: string | number; tone?: string }) { return <article className="stitch-card p-5"><p className="text-sm text-slate-600">{label}</p><strong className={`mt-2 block text-3xl ${tone}`}>{value}</strong></article>; }
const date = (value: string) => new Intl.DateTimeFormat("es-GT", { dateStyle: "short" }).format(new Date(value));
const due = (order: WorkOrder) => !!order.estimatedDate && order.status !== "COMPLETED" && new Date(order.estimatedDate) < new Date(new Date().toDateString());
