"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import type { Client, WorkOrder } from "@/shared/models/admin";
import { apiRequest } from "@/shared/services/api";
import { StatusBadge } from "@/shared/components/status-badge";
import { getErrorMessage } from "@/shared/utils/error-message";

type ClientForm = Pick<Client, "fullName" | "identificationType" | "identification"> & { phone: string; email: string; address: string };

export function ClientDetailView({ id }: { id: string }) {
  const [client, setClient] = useState<Client | null>(null); const [orders, setOrders] = useState<WorkOrder[]>([]); const [form, setForm] = useState<ClientForm | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { void Promise.all([apiRequest<{ client: Client }>(`/api/administrativo/clients/${id}`), apiRequest<{ items: WorkOrder[] }>(`/api/administrativo/clients/${id}/work-orders`)]).then(([clientResult, orderResult]) => { setClient(clientResult.client); setForm({ ...clientResult.client, phone: clientResult.client.phone ?? "", email: clientResult.client.email ?? "", address: clientResult.client.address ?? "" }); setOrders(orderResult.items); }).catch((caught: unknown) => setError(getErrorMessage(caught))); }, [id]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!form) return; setError(""); setMessage(""); try { const result = await apiRequest<{ client: Client }>(`/api/administrativo/clients/${id}`, { method: "PUT", body: JSON.stringify(form) }); setClient(result.client); setMessage("Cliente actualizado correctamente."); } catch (caught) { setError(getErrorMessage(caught)); } };
  if (!client || !form) return <p className="text-slate-500">{error || "Cargando cliente..."}</p>;
  const set = (key: keyof ClientForm, value: string) => setForm({ ...form, [key]: value });
  return <div className="mx-auto max-w-5xl"><div className="mb-6"><Link className="text-sm font-semibold text-blue-700" href="/administrativo/clientes">← Volver a clientes</Link><h2 className="mt-2 text-[28px] font-bold">{client.fullName}</h2><p className="text-slate-600">Edite los datos del cliente y consulte sus órdenes.</p></div>{error && <p role="alert" className="mb-4 rounded bg-red-50 p-3 text-red-800">{error}</p>}{message && <p role="status" className="mb-4 rounded bg-emerald-50 p-3 text-emerald-800">{message}</p>}<form onSubmit={submit} className="stitch-card p-6"><h3 className="font-semibold">Información del cliente</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Nombre completo"><input required className="stitch-input" value={form.fullName} onChange={(event) => set("fullName", event.target.value)} /></Field><Field label="Tipo de identificación"><select className="stitch-input" value={form.identificationType} onChange={(event) => set("identificationType", event.target.value)}><option>DPI</option><option>NIT</option><option>PASSPORT</option></select></Field><Field label="Identificación"><input required className="stitch-input" value={form.identification} onChange={(event) => set("identification", event.target.value)} /></Field><Field label="Teléfono"><input className="stitch-input" value={form.phone} onChange={(event) => set("phone", event.target.value)} /></Field><Field label="Correo"><input type="email" className="stitch-input" value={form.email} onChange={(event) => set("email", event.target.value)} /></Field><Field label="Dirección"><input className="stitch-input" value={form.address} onChange={(event) => set("address", event.target.value)} /></Field></div><div className="mt-5 flex justify-end"><button className="stitch-button stitch-button-primary">Guardar cambios</button></div></form><section className="stitch-card mt-6 overflow-hidden"><div className="border-b border-slate-200 p-4"><h3 className="font-semibold">Órdenes relacionadas</h3></div><div className="overflow-x-auto"><table className="stitch-table"><thead><tr><th>Código</th><th>Servicio</th><th>Estado</th><th>Avance</th><th>Asignado</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td><Link className="font-semibold text-blue-700" href={`/administrativo/ordenes/${order.id}`}>{order.code}</Link></td><td>{order.serviceType}</td><td><StatusBadge status={order.status} /></td><td>{order.progress}%</td><td>{order.assignedWorker ?? "Sin asignar"}</td></tr>)}{!orders.length && <tr><td colSpan={5} className="p-6 text-center text-slate-500">Este cliente todavía no tiene órdenes.</td></tr>}</tbody></table></div></section></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm font-medium text-slate-700"><span className="mb-1.5 block">{label}</span>{children}</label>; }
