"use client";

import { useCallback, useEffect, useState } from "react";
import type { Client, Paginated } from "@/shared/models/admin";
import { apiRequest } from "@/shared/services/api";

export function ClientsView() {
  const [data, setData] = useState<Paginated<Client> | null>(null); const [search, setSearch] = useState(""); const [identificationType, setIdentificationType] = useState(""); const [error, setError] = useState(""); const [selected, setSelected] = useState<Client | null>(null);
  const load = useCallback(async () => { try { const query = new URLSearchParams({ limit: "20" }); if (search) query.set("search", search); if (identificationType) query.set("identificationType", identificationType); setData(await apiRequest<Paginated<Client>>(`/api/admin/clients?${query}`)); } catch (caught) { setError((caught as Error).message); } }, [search, identificationType]);
  useEffect(() => { void load(); }, [load]);
  const detail = async (id: string) => { try { const result = await apiRequest<{ client: Client }>(`/api/admin/clients/${id}`); setSelected(result.client); } catch (caught) { setError((caught as Error).message); } };
  return <div className="mx-auto max-w-[1440px]"><div className="mb-6"><h2 className="text-[28px] font-bold">Lista de clientes</h2><p className="mt-1 text-slate-600">Consulte la información de los clientes registrados en el sistema.</p></div>{error && <p role="alert" className="mb-4 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    <section className="stitch-card mb-6 p-4"><div className="grid gap-4 md:grid-cols-[1fr_220px_auto] md:items-end"><label className="text-sm text-slate-600"><span className="mb-2 block">Buscar cliente</span><div className="relative"><span className="material-symbols-outlined absolute left-3 top-2.5 text-slate-500">search</span><input className="stitch-input pl-10" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Nombre, identificación o teléfono" /></div></label><label className="text-sm text-slate-600"><span className="mb-2 block">Tipo de identificación</span><select className="stitch-input" value={identificationType} onChange={(event) => setIdentificationType(event.target.value)}><option value="">Todos</option><option value="DPI">DPI</option><option value="NIT">NIT</option><option value="PASSPORT">Pasaporte</option></select></label><button className="stitch-button stitch-button-secondary" onClick={() => { setSearch(""); setIdentificationType(""); }}><span className="material-symbols-outlined">filter_alt_off</span>Limpiar</button></div></section>
    <section className="stitch-card overflow-hidden"><div className="overflow-x-auto"><table className="stitch-table"><thead><tr><th>Nombre</th><th>Identificación</th><th>Teléfono</th><th>Correo electrónico</th><th>Fecha de registro</th><th className="text-right">Acciones</th></tr></thead><tbody>{data?.items.map((client) => <tr key={client.id}><td className="font-medium">{client.fullName}</td><td>{client.identificationType}: {client.identification}</td><td className="text-slate-600">{client.phone ?? "—"}</td><td className="text-slate-600">{client.email ?? "—"}</td><td className="text-slate-600">{formatDate(client.createdAt)}</td><td className="text-right"><button aria-label={`Ver ${client.fullName}`} onClick={() => void detail(client.id)} className="rounded p-1.5 text-slate-500 hover:bg-slate-100 hover:text-blue-700"><span className="material-symbols-outlined">visibility</span></button></td></tr>)}{data && !data.items.length && <tr><td colSpan={6} className="p-10 text-center text-slate-500">No hay clientes que coincidan con los filtros.</td></tr>}</tbody></table></div><div className="border-t border-slate-300 px-4 py-3 text-sm text-slate-600">Mostrando {data?.items.length ?? 0} de {data?.total ?? 0} clientes</div></section>
    {selected && <div className="fixed inset-0 z-30 flex items-center justify-center bg-slate-950/40 p-4"><article className="stitch-card w-full max-w-lg p-6"><div className="flex justify-between"><div><h3 className="text-xl font-bold">Detalle de cliente</h3><p className="text-sm text-slate-500">Información registrada</p></div><button aria-label="Cerrar" onClick={() => setSelected(null)}><span className="material-symbols-outlined">close</span></button></div><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><Detail label="Nombre" value={selected.fullName} /><Detail label="Identificación" value={`${selected.identificationType}: ${selected.identification}`} /><Detail label="Teléfono" value={selected.phone ?? "No registrado"} /><Detail label="Correo" value={selected.email ?? "No registrado"} /><Detail label="Dirección" value={selected.address ?? "No registrada"} /></dl></article></div>}
  </div>;
}
function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 font-medium text-slate-800">{value}</dd></div>; }
const formatDate = (value: string) => new Intl.DateTimeFormat("es-GT", { dateStyle: "short" }).format(new Date(value));
