"use client";

import { FormEvent, useEffect, useState } from "react";
import type { AppSettings } from "@/shared/models/admin";
import { apiRequest } from "@/shared/services/api";

const defaults: AppSettings = { company: { name: "Motor Repair", phone: "", address: "" }, finance: { currency: "GTQ", taxRate: 0 } };
export function SettingsView() {
  const [settings, setSettings] = useState<AppSettings>(defaults); const [status, setStatus] = useState("");
  useEffect(() => { void apiRequest<{ settings: AppSettings }>("/api/admin/settings").then((result) => setSettings(result.settings)).catch((caught: Error) => setStatus(caught.message)); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setStatus(""); try { const result = await apiRequest<{ settings: AppSettings }>("/api/admin/settings", { method: "PUT", body: JSON.stringify(settings) }); setSettings(result.settings); setStatus("Configuración guardada correctamente."); } catch (caught) { setStatus((caught as Error).message); } };
  const company = (key: keyof AppSettings["company"], value: string) => setSettings({ ...settings, company: { ...settings.company, [key]: value } });
  return <div className="mx-auto max-w-3xl"><div className="mb-6"><h2 className="text-[28px] font-bold">Configuración</h2><p className="mt-1 text-slate-600">Defina los datos del taller y las reglas financieras base.</p></div>{status && <p role="status" className={`mb-4 rounded p-3 text-sm ${status.includes("correctamente") ? "bg-emerald-50 text-emerald-800" : "bg-red-50 text-red-800"}`}>{status}</p>}<form onSubmit={submit} className="space-y-5"><section className="stitch-card p-6"><h3 className="text-lg font-bold">Información del taller</h3><div className="mt-5 grid gap-4"><Field label="Nombre comercial"><input required className="stitch-input" value={settings.company.name} onChange={(e) => company("name", e.target.value)} /></Field><Field label="Teléfono"><input className="stitch-input" value={settings.company.phone} onChange={(e) => company("phone", e.target.value)} /></Field><Field label="Dirección"><textarea className="stitch-input h-20 py-2" value={settings.company.address} onChange={(e) => company("address", e.target.value)} /></Field></div></section><section className="stitch-card p-6"><h3 className="text-lg font-bold">Reglas financieras</h3><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Moneda"><input required maxLength={8} className="stitch-input" value={settings.finance.currency} onChange={(e) => setSettings({ ...settings, finance: { ...settings.finance, currency: e.target.value.toUpperCase() } })} /></Field><Field label="Impuesto (%)"><input required min="0" max="100" step="0.01" type="number" className="stitch-input" value={settings.finance.taxRate} onChange={(e) => setSettings({ ...settings, finance: { ...settings.finance, taxRate: Number(e.target.value) } })} /></Field></div></section><div className="flex justify-end"><button className="stitch-button stitch-button-primary">Guardar configuración</button></div></form></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium text-slate-700"><span className="mb-1.5 block">{label}</span>{children}</label>; }
