import { beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({ create: vi.fn(), createMovement: vi.fn(), findById: vi.fn(), update: vi.fn(), setStatus: vi.fn(), list: vi.fn(), dashboard: vi.fn(), movements: vi.fn(), allocations: vi.fn(), allocate: vi.fn(), release: vi.fn(), activeWorkOrders: vi.fn(), audit: vi.fn(), orderFind: vi.fn() }));
vi.mock("../src/repositories/inventory.repository", () => ({ InventoryRepository: class { create = mocks.create; createMovement = mocks.createMovement; findById = mocks.findById; update = mocks.update; setStatus = mocks.setStatus; list = mocks.list; dashboard = mocks.dashboard; movements = mocks.movements; allocations = mocks.allocations; allocate = mocks.allocate; release = mocks.release; activeWorkOrders = mocks.activeWorkOrders; } }));
vi.mock("../src/repositories/work-order.repository", () => ({ WorkOrderRepository: class { findById = mocks.orderFind; } }));
vi.mock("../src/services/audit.service", () => ({ AuditService: class { record = mocks.audit; } }));
import { InventoryService } from "../src/services/inventory.service";

const input = { code: "ACE-1", name: "Aceite", type: "CONSUMABLE" as const, category: "Lubricantes", brand: null, partNumber: null, description: null, compatibility: null, unit: "litro", location: null, minimumStock: 1, initialStock: 4, referenceUnitCost: 20, referenceSupplier: null, isActive: true };
describe("inventory service", () => {
  beforeEach(() => vi.clearAllMocks());
  it("records creation and initial stock audit", async () => { mocks.create.mockResolvedValue({ id: "item", sku: "ACE-1" }); await new InventoryService().createItem(input, "actor"); expect(mocks.audit).toHaveBeenCalledWith("actor", "INVENTORY_ITEM_CREATED", "INVENTORY_ITEM", "item", expect.any(Object)); expect(mocks.audit).toHaveBeenCalledWith("actor", "INVENTORY_ENTRY_CREATED", "INVENTORY_ITEM", "item", expect.objectContaining({ resultingStock: 4 })); });
  it("translates duplicate codes into a conflict", async () => { mocks.create.mockRejectedValue({ code: "23505" }); await expect(new InventoryService().createItem(input, "actor")).rejects.toMatchObject({ statusCode: 409, code: "INVENTORY_CODE_EXISTS" }); });
  it("returns stock context and does not audit a rejected exit", async () => { mocks.createMovement.mockRejectedValue(Object.assign(new Error("INSUFFICIENT_STOCK"), { availableStock: 2 })); await expect(new InventoryService().exit("item", { quantity: 5, reason: "Otro", referenceDocument: null, supplierReference: null, workOrderId: null, observation: null }, "actor")).rejects.toMatchObject({ statusCode: 409, code: "INSUFFICIENT_STOCK", details: { availableStock: 2, requestedQuantity: 5, missingQuantity: 3 } }); expect(mocks.audit).not.toHaveBeenCalled(); });
  it("records a successful movement with authenticated actor", async () => { mocks.createMovement.mockResolvedValue({ id: "movement", previousStock: 4, resultingStock: 3, quantity: 1, reason: "Otro", workOrderId: null }); await new InventoryService().exit("item", { quantity: 1, reason: "Otro", referenceDocument: null, supplierReference: null, workOrderId: null, observation: null }, "actor"); expect(mocks.createMovement).toHaveBeenCalledWith("item", "EXIT", expect.any(Object), "actor"); expect(mocks.audit).toHaveBeenCalledWith("actor", "INVENTORY_EXIT_CREATED", "INVENTORY_MOVEMENT", "movement", expect.any(Object)); });
});
