import { ITEM_TYPE_LABELS, stockState } from "@/modules/inventory/models/inventory";
import { StatusBadge } from "@/shared/components/status-badge";
import type { ReportClient, ReportFinance, ReportInventory, ReportInventoryMovement, ReportOrder } from "../models/reports";
import { date, money } from "./report-ui";

export function OrdersTable({ items }: { items: ReportOrder[] }) { return <Table headers={["Orden", "Cliente", "Motor / servicio", "Estado", "Asignación", "Finanzas", "Fecha"]}>{items.map((item) => <tr key={item.id}><td className="font-bold text-blue-700">{item.code}</td><td>{item.clientName}</td><td><strong>{item.engineBrand} {item.engineModel}</strong><small className="mt-1 block text-slate-500">{item.serviceType}</small></td><td><StatusBadge status={item.status} /></td><td>{item.assignedWorker ?? "Sin asignar"}</td><td><span className="block">Total: {item.totalAmount === null ? "Sin definir" : money(item.totalAmount)}</span><small className="text-slate-500">Pagado: {money(item.totalPaid)} · Saldo: {item.balance === null ? "—" : money(item.balance)}</small></td><td>{date(item.createdAt)}</td></tr>)}</Table>; }

export function ClientsTable({ items }: { items: ReportClient[] }) { return <Table headers={["Cliente", "Identificación", "Contacto", "Actividad de órdenes", "Última orden"]}>{items.map((item) => <tr key={item.id}><td className="font-semibold">{item.fullName}</td><td>{item.identificationType}: {item.identification}</td><td><span className="block">{item.phone ?? "—"}</span><small className="text-slate-500">{item.email ?? "Sin correo"}</small></td><td><strong>{item.orderCount} total</strong><small className="mt-1 block text-slate-500">{item.pendingOrders} pendientes · {item.inProgressOrders} en proceso · {item.completedOrders} finalizadas · {item.cancelledOrders} canceladas</small></td><td>{date(item.lastOrderAt)}</td></tr>)}</Table>; }

export function InventoryTable({ items }: { items: ReportInventory[] }) { return <Table headers={["Artículo", "Tipo / categoría", "Stock", "Mínimo", "Estado"]}>{items.map((item) => { const state = stockState(item); return <tr key={item.id}><td><strong>{item.name}</strong><small className="mt-1 block text-slate-500">{item.sku}</small></td><td>{ITEM_TYPE_LABELS[item.type]}<small className="mt-1 block text-slate-500">{item.category}</small></td><td className="font-semibold">{item.stockQuantity} {item.unit}</td><td>{item.minimumStock} {item.unit}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${state.className}`}>{state.label}</span></td></tr>; })}</Table>; }

export function MovementsTable({ items }: { items: ReportInventoryMovement[] }) { return <Table headers={["Fecha", "Artículo", "Movimiento", "Cantidad", "Motivo", "Responsable", "Orden"]}>{items.map((item) => <tr key={item.id}><td>{date(item.createdAt)}</td><td><strong>{item.itemName}</strong><small className="mt-1 block text-slate-500">{item.itemCode}</small></td><td>{item.movementType === "ENTRY" ? "Entrada" : item.movementType === "EXIT" ? "Salida" : "Ajuste"}</td><td className="font-semibold">{item.quantity}</td><td>{item.reason}</td><td>{item.performedByName ?? "—"}</td><td>{item.workOrderCode ?? "—"}</td></tr>)}</Table>; }

export function FinanceTable({ items }: { items: ReportFinance[] }) { return <Table headers={["Fecha", "Orden", "Cliente", "Método", "Referencia", "Recibido por", "Monto"]}>{items.map((item) => <tr key={item.id}><td>{date(item.createdAt)}</td><td className="font-bold text-blue-700">{item.workOrderCode}</td><td>{item.clientName}</td><td>{item.method}</td><td>{item.reference ?? "—"}</td><td>{item.receivedBy ?? "—"}</td><td className="font-bold text-emerald-700">{money(item.amount)}</td></tr>)}</Table>; }

function Table({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <div className="overflow-x-auto"><table className="stitch-table"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }

