import type { CreateInventoryItemDto } from "../dtos/admin.dtos";
import type { CreateInventoryItemInput, InventoryListFilters, InventoryMovementFilters, InventoryMovementInput, UpdateInventoryItemInput } from "../dtos/inventory.dtos";
import { InventoryRepository } from "../repositories/inventory.repository";
import { WorkOrderRepository } from "../repositories/work-order.repository";
import { AppError } from "../utils/app-error";
import { AuditService } from "./audit.service";

export class InventoryService {
  private readonly inventory = new InventoryRepository(); private readonly orders = new WorkOrderRepository(); private readonly audit = new AuditService();
  async list(search?: string) { return (await this.inventory.list({ search, page: 1, limit: 100 })).items; }
  listItems(filters: InventoryListFilters) { return this.inventory.list(filters); }
  async getItem(id: string) { const item = await this.inventory.findById(id); if (!item) throw new AppError("Producto no encontrado", 404, "INVENTORY_NOT_FOUND"); return item; }
  async create(input: CreateInventoryItemDto, actorId: string) { return this.createItem({ code: input.sku, name: input.name, type: "PART", category: "Otros", brand: null, partNumber: null, description: input.description ?? null, compatibility: null, unit: input.unit, location: null, minimumStock: input.minimumStock, initialStock: input.stockQuantity, referenceUnitCost: 0, referenceSupplier: null, isActive: true }, actorId); }
  async createItem(input: CreateInventoryItemInput, actorId: string) { try { const item = await this.inventory.create(input, actorId); await this.audit.record(actorId, "INVENTORY_ITEM_CREATED", "INVENTORY_ITEM", item.id, { code: item.sku, initialStock: input.initialStock }); if (input.initialStock > 0) await this.audit.record(actorId, "INVENTORY_ENTRY_CREATED", "INVENTORY_ITEM", item.id, { reason: "Existencia inicial", previousStock: 0, resultingStock: input.initialStock }); return item; } catch (error) { if ((error as { code?: string }).code === "23505") throw new AppError("Ya existe un artículo con ese código", 409, "INVENTORY_CODE_EXISTS"); throw error; } }
  async updateItem(id: string, input: UpdateInventoryItemInput, actorId: string) { const item = await this.inventory.update(id, input, actorId); if (!item) throw new AppError("Producto no encontrado", 404, "INVENTORY_NOT_FOUND"); await this.audit.record(actorId, "INVENTORY_ITEM_UPDATED", "INVENTORY_ITEM", id, { code: item.sku }); return item; }
  async setStatus(id: string, isActive: boolean, actorId: string) { const item = await this.inventory.setStatus(id, isActive, actorId); if (!item) throw new AppError("Producto no encontrado", 404, "INVENTORY_NOT_FOUND"); await this.audit.record(actorId, isActive ? "INVENTORY_ITEM_ACTIVATED" : "INVENTORY_ITEM_DEACTIVATED", "INVENTORY_ITEM", id); return item; }
  entry(itemId: string, input: InventoryMovementInput, actorId: string) { return this.movement(itemId, "ENTRY", input, actorId); }
  exit(itemId: string, input: InventoryMovementInput, actorId: string) { return this.movement(itemId, "EXIT", input, actorId); }
  private async movement(itemId: string, type: "ENTRY" | "EXIT", input: InventoryMovementInput, actorId: string) { try { const movement = await this.inventory.createMovement(itemId, type, input, actorId); await this.audit.record(actorId, type === "ENTRY" ? "INVENTORY_ENTRY_CREATED" : "INVENTORY_EXIT_CREATED", "INVENTORY_MOVEMENT", movement.id, { inventoryItemId: itemId, previousStock: movement.previousStock, resultingStock: movement.resultingStock, quantity: movement.quantity, reason: movement.reason, workOrderId: movement.workOrderId }); return movement; } catch (error) { const code = (error as Error).message; if (code === "ITEM_NOT_FOUND") throw new AppError("Producto no encontrado", 404, "INVENTORY_NOT_FOUND"); if (code === "ITEM_INACTIVE") throw new AppError("No se pueden registrar movimientos para un producto inactivo", 409, "INVENTORY_ITEM_INACTIVE"); if (code === "WORK_ORDER_NOT_ACTIVE") throw new AppError("La orden relacionada no está activa", 422, "WORK_ORDER_NOT_ACTIVE"); if (code === "INSUFFICIENT_STOCK") { const availableStock = (error as Error & { availableStock?: number }).availableStock ?? 0; throw new AppError("Existencia insuficiente para realizar la salida", 409, "INSUFFICIENT_STOCK", { availableStock, requestedQuantity: input.quantity, missingQuantity: input.quantity - availableStock }); } throw error; } }
  movements(filters: InventoryMovementFilters) { return this.inventory.movements(filters); }
  dashboard() { return this.inventory.dashboard(); }
  activeWorkOrders() { return this.inventory.activeWorkOrders(); }
  async allocations(orderId: string) { if (!await this.orders.findById(orderId)) throw new AppError("Orden no encontrada", 404, "WORK_ORDER_NOT_FOUND"); return this.inventory.allocations(orderId); }
  async allocate(orderId: string, itemId: string, quantity: number, actorId: string) { if (!await this.orders.findById(orderId)) throw new AppError("Orden no encontrada", 404, "WORK_ORDER_NOT_FOUND"); try { await this.inventory.allocate(orderId, itemId, quantity, actorId); await this.audit.record(actorId, "INVENTORY_ASSIGNED", "WORK_ORDER", orderId, { inventoryItemId: itemId, quantity }); return this.inventory.allocations(orderId); } catch (error) { if ((error as Error).message === "ITEM_NOT_FOUND") throw new AppError("Artículo de inventario no encontrado", 404, "INVENTORY_NOT_FOUND"); if ((error as Error).message === "INSUFFICIENT_STOCK") throw new AppError("No hay existencias suficientes", 409, "INSUFFICIENT_STOCK"); throw error; } }
  async release(orderId: string, itemId: string, actorId: string) { if (!await this.inventory.release(orderId, itemId, actorId)) throw new AppError("Asignación de inventario no encontrada", 404, "ASSIGNMENT_NOT_FOUND"); await this.audit.record(actorId, "INVENTORY_RELEASED", "WORK_ORDER", orderId, { inventoryItemId: itemId }); return this.inventory.allocations(orderId); }
}
