import { databasePool } from "../config/database";
import type { CashierOrderFilters, CashierPaymentFilters } from "../dtos/cashier.dtos";
import type { CashierDashboard, CashierDailySummary, CashierOrder, Payment } from "../models/domain";
import { computeFinancialStatus } from "./payment.repository";

const mapPayment = (row: Record<string, unknown>): Payment => ({ id: String(row.id), workOrderId: String(row.work_order_id), workOrderCode: String(row.work_order_code), clientName: String(row.client_name), amount: Number(row.amount), method: String(row.method), reference: row.reference as string | null, notes: row.notes as string | null, receivedBy: row.received_by_name as string | null, createdAt: String(row.created_at) });
const mapOrder = (row: Record<string, unknown>): CashierOrder => { const totalAmount = row.total_amount === null ? null : Number(row.total_amount); const totalPaid = Number(row.total_paid); const balance = totalAmount === null ? null : Math.max(0, Number((totalAmount - totalPaid).toFixed(2))); return { workOrderId: String(row.work_order_id), workOrderCode: String(row.work_order_code), clientName: String(row.client_name), totalAmount, totalPaid, balance, financialStatus: computeFinancialStatus(totalAmount, totalPaid, balance), operationalStatus: row.operational_status as CashierOrder["operationalStatus"], createdAt: String(row.created_at) }; };
const paymentSelect = `SELECT p.*,o.code AS work_order_code,c.full_name AS client_name,u.full_name AS received_by_name FROM payments p JOIN work_orders o ON o.id=p.work_order_id JOIN clients c ON c.id=o.client_id LEFT JOIN app_users u ON u.id=p.received_by`;
const summaries = `SELECT o.id AS work_order_id,o.code AS work_order_code,c.full_name AS client_name,o.status AS operational_status,o.created_at,o.total_amount,COALESCE(SUM(p.amount),0)::numeric(12,2) AS total_paid FROM work_orders o JOIN clients c ON c.id=o.client_id LEFT JOIN payments p ON p.work_order_id=o.id GROUP BY o.id,c.full_name`;
export class CashierRepository {
  async orders(filters: CashierOrderFilters) { const params: unknown[]=[]; const clauses:string[]=[]; if(filters.search){params.push(`%${filters.search}%`);clauses.push(`(work_order_code ILIKE $${params.length} OR client_name ILIKE $${params.length})`);} if(filters.financialStatus){params.push(filters.financialStatus);clauses.push(`financial_status=$${params.length}`);} const where=clauses.length?`WHERE ${clauses.join(" AND ")}`:""; const query=`WITH base AS (${summaries}), listed AS (SELECT *,CASE WHEN total_amount IS NULL THEN 'PENDING' WHEN total_paid >= total_amount THEN 'PAID' WHEN total_paid > 0 THEN 'PARTIAL' ELSE 'PENDING' END AS financial_status FROM base) SELECT * FROM listed ${where}`; const total=await databasePool.query(`SELECT count(*)::int AS count FROM (${query}) q`,params);params.push(filters.limit,(filters.page-1)*filters.limit);const rows=await databasePool.query(`${query} ORDER BY created_at DESC LIMIT $${params.length-1} OFFSET $${params.length}`,params);return {items:rows.rows.map(mapOrder),total:total.rows[0].count,page:filters.page,limit:filters.limit}; }
  async payments(filters: CashierPaymentFilters) { const params:unknown[]=[];const clauses:string[]=[];const add=(sql:string,value:unknown)=>{params.push(value);clauses.push(sql.replace("?",`$${params.length}`));};if(filters.search)add("(o.code ILIKE ? OR c.full_name ILIKE ? OR p.reference ILIKE ?)",`%${filters.search}%`);if(filters.method)add("p.method=$?",filters.method);if(filters.cashierId)add("p.received_by=$?",filters.cashierId);if(filters.startDate)add("p.created_at >= ?::date",filters.startDate);if(filters.endDate)add("p.created_at < (?::date + interval '1 day')",filters.endDate); const where=clauses.length?`WHERE ${clauses.join(" AND ")}`:"";const total=await databasePool.query(`SELECT count(*)::int AS count FROM payments p JOIN work_orders o ON o.id=p.work_order_id JOIN clients c ON c.id=o.client_id ${where}`,params);params.push(filters.limit,(filters.page-1)*filters.limit);const rows=await databasePool.query(`${paymentSelect} ${where} ORDER BY p.created_at DESC LIMIT $${params.length-1} OFFSET $${params.length}`,params);return {items:rows.rows.map(mapPayment),total:total.rows[0].count,page:filters.page,limit:filters.limit}; }
  async payment(id:string){const result=await databasePool.query(`${paymentSelect} WHERE p.id=$1`,[id]);return result.rowCount?mapPayment(result.rows[0]):null;}
  async daily(actorId?:string):Promise<CashierDailySummary>{const today=`(now() AT TIME ZONE 'America/Guatemala')::date`;const filter=actorId?"AND p.received_by=$1":"";const values=actorId?[actorId]:[];const r=await databasePool.query(`SELECT ${today}::text AS business_date,count(p.*)::int AS payment_count,COALESCE(sum(p.amount),0)::numeric AS total_amount,COALESCE(sum(p.amount) FILTER (WHERE lower(p.method) IN ('efectivo','cash')),0)::numeric AS cash_amount,COALESCE(sum(p.amount) FILTER (WHERE lower(p.method) IN ('transferencia','transfer')),0)::numeric AS transfer_amount,COALESCE(sum(p.amount) FILTER (WHERE lower(p.method) NOT IN ('efectivo','cash','transferencia','transfer')),0)::numeric AS other_amount,count(DISTINCT p.work_order_id)::int AS paid_orders FROM payments p WHERE (p.created_at AT TIME ZONE 'America/Guatemala')::date=${today} ${filter}`,values);const row=r.rows[0];const pending=await databasePool.query(`SELECT count(*)::int AS count FROM (${summaries}) q WHERE total_amount IS NOT NULL AND total_paid < total_amount`);return {businessDate:row.business_date,cashierName:null,paymentCount:row.payment_count,totalAmount:Number(row.total_amount),cashAmount:Number(row.cash_amount),transferAmount:Number(row.transfer_amount),otherAmount:Number(row.other_amount),paidOrders:row.paid_orders,pendingOrders:pending.rows[0].count,partialPayments:0,finalPayments:0};}
  async dashboard(actorId:string):Promise<CashierDashboard>{const [summary,recent,pending]=await Promise.all([this.daily(actorId),databasePool.query(`${paymentSelect} WHERE p.received_by=$1 ORDER BY p.created_at DESC LIMIT 6`,[actorId]),this.orders({page:1,limit:6})]);return {...summary,recentPayments:recent.rows.map(mapPayment),pendingOrders:pending.items.filter((x)=>x.balance!==null&&x.balance>0)};}
}
