"use client";
import { FormEvent, useEffect, useState } from "react";
import { ApiError } from "@/shared/services/api";
import type { MovementPayload } from "../dtos/inventory.dto";
import { ENTRY_REASONS, EXIT_REASONS, type InventoryItem } from "../models/inventory";

const blank = (kind: "ENTRY" | "EXIT"): MovementPayload => ({ quantity: 1, reason: kind === "ENTRY" ? ENTRY_REASONS[0] : EXIT_REASONS[0], referenceDocument: null, supplierReference: null, workOrderId: null, observation: null });
export function InventoryMovementDialog({ item, kind, workOrders, onClose, onSubmit }: { item: InventoryItem; kind: "ENTRY" | "EXIT"; workOrders: { id: string; code: string }[]; onClose: () => void; onSubmit: (input: MovementPayload) => Promise<void> }) {
  const [form, setForm] = useState(blank(kind)); const [error, setError] = useState(""); const [insufficient, setInsufficient] = useState<{ available: number; requested: number; missing: number } | null>(null); const [saving, setSaving] = useState(false); const entry = kind === "ENTRY"; const result = entry ? item.stockQuantity + form.quantity : item.stockQuantity - form.quantity;
  useEffect(() => { setForm(blank(kind)); setError(""); setInsufficient(null); }, [kind, item.id]);
  const setText = (key: keyof MovementPayload, value: string) => setForm((previous) => ({ ...previous, [key]: value.trim() || null }));
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); setInsufficient(null); if (!Number.isFinite(form.quantity) || form.quantity <= 0) { setError("La cantidad debe ser mayor que cero."); return; } try { setSaving(true); await onSubmit(form); } catch (caught) { if (caught instanceof ApiError && caught.code === "INSUFFICIENT_STOCK") { const details = caught.details ?? {}; setInsufficient({ available: Number(details.availableStock ?? item.stockQuantity), requested: Number(details.requestedQuantity ?? form.quantity), missing: Number(details.missingQuantity ?? Math.max(0, form.quantity - item.stockQuantity)) }); } else setError((caught as Error).message); } finally { setSaving(false); } };
  if (insufficient) return <Dialog title="Stock insuficiente" onClose={onClose}><div className="space-y-5"><div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-amber-900"><strong>La salida no fue registrada.</strong><p className="mt-1 text-sm">Solicitaste {insufficient.requested} {item.unit}; hay {insufficient.available} disponibles.</p></div><div className="grid grid-cols-3 gap-3 text-center text-sm"><Metric label="Solicitado" value={insufficient.requested} /><Metric label="Disponible" value={insufficient.available} /><Metric label="Faltante" value={insufficient.missing} /></div><div className="h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-amber-500" style={{ width: `${Math.min(100, insufficient.available / insufficient.requested * 100)}%` }} /></div><div className="flex flex-wrap justify-end gap-2"><button className="stitch-button stitch-button-secondary" onClick={onClose}>Cancelar</button><button className="stitch-button stitch-button-secondary" onClick={() => setInsufficient(null)}>Corregir cantidad</button><button className="stitch-button stitch-button-primary" onClick={() => { setForm((previous) => ({ ...previous, quantity: insufficient.available })); setInsufficient(null); }}>Usar máximo disponible</button></div></div></Dialog>;
  return <Dialog title={entry ? "Registrar entrada" : "Registrar salida"} onClose={onClose}><form onSubmit={(event) => void submit(event)} className="space-y-4"><div className="rounded-lg bg-slate-50 p-3 text-sm"><strong>{item.name}</strong><div className="mt-1 flex justify-between text-slate-600"><span>Disponible: {item.stockQuantity} {item.unit}</span><span>Mínimo: {item.minimumStock}</span></div></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Cantidad<input autoFocus min="0.01" step="0.01" type="number" className="stitch-input mt-1.5" value={form.quantity} onChange={(e) => setForm((previous) => ({ ...previous, quantity: Number(e.target.value) }))} /></label><label className="text-sm font-medium">Existencia resultante<div className={`stitch-input mt-1.5 flex items-center ${result < 0 ? "border-red-400 bg-red-50 text-red-700" : "bg-slate-50"}`}>{result} {item.unit}</div></label><label className="text-sm font-medium sm:col-span-2">Motivo<select className="stitch-input mt-1.5" value={form.reason} onChange={(e) => setForm((previous) => ({ ...previous, reason: e.target.value, workOrderId: e.target.value === "Uso en reparación" ? previous.workOrderId : null }))}>{(entry ? ENTRY_REASONS : EXIT_REASONS).map((reason) => <option key={reason}>{reason}</option>)}</select></label>{!entry && form.reason === "Uso en reparación" && <label className="text-sm font-medium sm:col-span-2">Orden de trabajo activa<select required className="stitch-input mt-1.5" value={form.workOrderId ?? ""} onChange={(e) => setForm((previous) => ({ ...previous, workOrderId: e.target.value || null }))}><option value="">Seleccione una orden</option>{workOrders.map((order) => <option key={order.id} value={order.id}>{order.code}</option>)}</select></label>}<label className="text-sm font-medium">Factura / referencia<input className="stitch-input mt-1.5" onChange={(e) => setText("referenceDocument", e.target.value)} /></label>{entry && <label className="text-sm font-medium">Proveedor<input className="stitch-input mt-1.5" onChange={(e) => setText("supplierReference", e.target.value)} /></label>}<label className="text-sm font-medium sm:col-span-2">Observación<textarea className="stitch-input mt-1.5 min-h-20 py-2" onChange={(e) => setText("observation", e.target.value)} /></label></div>{error && <p role="alert" className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}<p className="text-xs text-slate-500">El responsable y la fecha se registran desde tu sesión.</p><div className="flex justify-end gap-2"><button type="button" className="stitch-button stitch-button-secondary" onClick={onClose}>Cancelar</button><button disabled={saving} className="stitch-button stitch-button-primary">{saving ? "Registrando..." : entry ? "Confirmar entrada" : "Confirmar salida"}</button></div></form></Dialog>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded border border-slate-200 p-2"><strong className="block text-lg">{value}</strong><span className="text-slate-500">{label}</span></div>; }
function Dialog({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4"><section role="dialog" aria-modal="true" aria-label={title} className="stitch-card max-h-[92vh] w-full max-w-2xl overflow-y-auto p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-bold">{title}</h2><button aria-label="Cerrar" className="rounded p-1 text-slate-500 hover:bg-slate-100" onClick={onClose}>×</button></div>{children}</section></div>; }
