"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import type { InventoryItem } from "@/shared/models/admin";
import { apiRequest } from "@/shared/services/api";
import { Icon } from "@/shared/components/icon";

const empty = { sku: "", name: "", description: "", unit: "unidad", stockQuantity: "0", minimumStock: "0" };
export function InventoryView() {
  const [items, setItems] = useState<InventoryItem[]>([]); const [search, setSearch] = useState(""); const [form, setForm] = useState(empty); const [adding, setAdding] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { try { const query = search ? `?search=${encodeURIComponent(search)}` : ""; setItems((await apiRequest<{ items: InventoryItem[] }>(`/api/admin/inventory${query}`)).items); } catch (caught) { setError((caught as Error).message); } }, [search]);
  useEffect(() => { void load(); }, [load]);
  const submit = async (event: FormEvent) => { event.preventDefault(); try { await apiRequest("/api/admin/inventory", { method: "POST", body: JSON.stringify({ ...form, stockQuantity: Number(form.stockQuantity), minimumStock: Number(form.minimumStock) }) }); setForm(empty); setAdding(false); await load(); } catch (caught) { setError((caught as Error).message); } };
  const set = (key: keyof typeof empty, value: string) => setForm({ ...form, [key]: value });
  return <div className="mx-auto max-w-[1440px]"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-[28px] font-bold">Inventario</h2><p className="mt-1 text-slate-600">Controle existencias e insumos; los materiales se asignan desde cada orden.</p></div><button className="stitch-button stitch-button-primary" onClick={() => setAdding(true)}><Icon name="add" />Nuevo artículo</button></div>{error && <p role="alert" className="mb-4 rounded bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    <label className="mb-5 block max-w-lg text-sm text-slate-600">Buscar por código o nombre<input value={search} onChange={(event) => setSearch(event.target.value)} className="stitch-input mt-1.5" placeholder="Ej. Filtro, FIL-001" /></label>
    <section className="stitch-card overflow-hidden"><div className="overflow-x-auto"><table className="stitch-table"><thead><tr><th>Código</th><th>Artículo</th><th>Unidad</th><th>Existencia</th><th>Mínimo</th><th>Estado</th></tr></thead><tbody>{items.map((item) => { const low = item.stockQuantity <= item.minimumStock; return <tr key={item.id}><td className="font-medium text-blue-700">{item.sku}</td><td><strong>{item.name}</strong>{item.description && <small className="mt-1 block text-slate-500">{item.description}</small>}</td><td>{item.unit}</td><td>{item.stockQuantity}</td><td>{item.minimumStock}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${low ? "bg-amber-100 text-amber-800" : "bg-emerald-100 text-emerald-800"}`}>{low ? "Stock bajo" : "Disponible"}</span></td></tr>; })}{!items.length && <tr><td colSpan={6} className="p-10 text-center text-slate-500">No se encontraron artículos.</td></tr>}</tbody></table></div></section>
    {adding && <div className="fixed inset-0 z-30 flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={submit} className="stitch-card w-full max-w-lg p-6"><div className="flex justify-between"><h3 className="text-xl font-bold">Nuevo artículo</h3><button type="button" onClick={() => setAdding(false)}><Icon name="close" /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Código"><input required className="stitch-input" value={form.sku} onChange={(e) => set("sku", e.target.value)} /></Field><Field label="Nombre"><input required className="stitch-input" value={form.name} onChange={(e) => set("name", e.target.value)} /></Field><Field label="Unidad"><input required className="stitch-input" value={form.unit} onChange={(e) => set("unit", e.target.value)} /></Field><Field label="Existencia inicial"><input required min="0" step="0.01" type="number" className="stitch-input" value={form.stockQuantity} onChange={(e) => set("stockQuantity", e.target.value)} /></Field><Field label="Stock mínimo"><input required min="0" step="0.01" type="number" className="stitch-input" value={form.minimumStock} onChange={(e) => set("minimumStock", e.target.value)} /></Field><Field label="Descripción"><input className="stitch-input" value={form.description} onChange={(e) => set("description", e.target.value)} /></Field></div><div className="mt-6 flex justify-end gap-2"><button type="button" className="stitch-button stitch-button-secondary" onClick={() => setAdding(false)}>Cancelar</button><button className="stitch-button stitch-button-primary">Guardar artículo</button></div></form></div>}</div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm font-medium text-slate-700"><span className="mb-1.5 block">{label}</span>{children}</label>; }
