"use client";

import { useCallback, useEffect, useState } from "react";
import type { AppUser, AuditEvent, Paginated } from "@/shared/models/admin";
import { apiRequest } from "@/shared/services/api";

export function AuditView() {
  const [data, setData] = useState<Paginated<AuditEvent> | null>(null); const [users, setUsers] = useState<AppUser[]>([]); const [userId, setUserId] = useState(""); const [action, setAction] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [error, setError] = useState(""); const [selected, setSelected] = useState<AuditEvent | null>(null);
  const load = useCallback(async () => { try { const query = new URLSearchParams({ limit: "30" }); if (userId) query.set("userId", userId); if (action) query.set("action", action); if (from) query.set("from", from); if (to) query.set("to", to); setData(await apiRequest<Paginated<AuditEvent>>(`/api/admin/audit?${query}`)); } catch (caught) { setError((caught as Error).message); } }, [userId, action, from, to]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { void apiRequest<Paginated<AppUser>>("/api/admin/users?limit=100").then((result) => setUsers(result.items)).catch((caught: Error) => setError(caught.message)); }, []);
  return <div className="mx-auto max-w-[1440px]"><div className="mb-6"><h2 className="text-[28px] font-bold">Historial de auditoría</h2><p className="mt-1 text-slate-600">Consulta de solo lectura de acciones registradas en el sistema.</p></div>{error && <p role="alert" className="mb-4 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    <section className="stitch-card mb-6 grid gap-4 p-4 md:grid-cols-[1fr_220px_180px_180px_auto] md:items-end"><label className="text-sm text-slate-600"><span className="mb-2 block">Operación</span><input className="stitch-input" value={action} onChange={(event) => setAction(event.target.value)} placeholder="Ej. USER_CREATED" /></label><label className="text-sm text-slate-600"><span className="mb-2 block">Usuario</span><select className="stitch-input" value={userId} onChange={(event) => setUserId(event.target.value)}><option value="">Todos los usuarios</option>{users.map((user) => <option value={user.id} key={user.id}>{user.fullName}</option>)}</select></label><label className="text-sm text-slate-600"><span className="mb-2 block">Desde</span><input className="stitch-input" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label className="text-sm text-slate-600"><span className="mb-2 block">Hasta</span><input className="stitch-input" type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><button className="stitch-button stitch-button-secondary" onClick={() => { setUserId(""); setAction(""); setFrom(""); setTo(""); }}><span className="material-symbols-outlined">filter_alt_off</span>Limpiar</button></section>
    <section className="stitch-card overflow-hidden"><div className="overflow-x-auto"><table className="stitch-table"><thead><tr><th>Fecha y hora</th><th>Usuario</th><th>Operación</th><th>Entidad</th><th className="text-right">Detalle</th></tr></thead><tbody>{data?.items.map((event) => <tr key={event.id}><td className="text-slate-600">{formatDateTime(event.createdAt)}</td><td>{event.actorName ?? "Sistema"}</td><td><span className="rounded bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-700">{event.action}</span></td><td>{event.entityType}</td><td className="text-right"><button onClick={() => setSelected(event)} aria-label={`Detalle de ${event.action}`} className="rounded p-1.5 text-slate-500 hover:bg-slate-100 hover:text-blue-700"><span className="material-symbols-outlined">visibility</span></button></td></tr>)}{data && !data.items.length && <tr><td colSpan={5} className="p-10 text-center text-slate-500">No hay eventos de auditoría con esos filtros.</td></tr>}</tbody></table></div><div className="border-t border-slate-300 px-4 py-3 text-sm text-slate-600">Mostrando {data?.items.length ?? 0} de {data?.total ?? 0} eventos</div></section>
    {selected && <div className="fixed inset-0 z-30 flex items-center justify-center bg-slate-950/40 p-4"><article className="stitch-card w-full max-w-lg p-6"><div className="flex justify-between"><div><h3 className="text-xl font-bold">Detalle de evento</h3><p className="text-sm text-slate-500">Solo lectura</p></div><button onClick={() => setSelected(null)} aria-label="Cerrar"><span className="material-symbols-outlined">close</span></button></div><dl className="mt-5 grid gap-4 text-sm"><Entry label="Fecha" value={formatDateTime(selected.createdAt)} /><Entry label="Usuario" value={selected.actorName ?? "Sistema"} /><Entry label="Operación" value={selected.action} /><Entry label="Entidad" value={selected.entityType} /><Entry label="Datos registrados" value={JSON.stringify(selected.details, null, 2)} pre /></dl></article></div>}
  </div>;
}
function Entry({ label, value, pre }: { label: string; value: string; pre?: boolean }) { return <div><dt className="text-xs text-slate-500">{label}</dt><dd className={`mt-1 font-medium ${pre ? "whitespace-pre-wrap rounded bg-slate-50 p-3 font-mono text-xs" : ""}`}>{value}</dd></div>; }
const formatDateTime = (value: string) => new Intl.DateTimeFormat("es-GT", { dateStyle: "short", timeStyle: "short" }).format(new Date(value));
