"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { ApiError, apiRequest } from "@/shared/services/api";
import type { AppUser, Paginated, Role } from "@/shared/models/admin";
import { StatusBadge } from "@/shared/components/status-badge";
import { Icon } from "@/shared/components/icon";

const roleLabels: Record<Role, string> = { ADMIN: "Administrador", ADMINISTRATIVE: "Personal Administrativo", CASHIER: "Cajero", INVENTORY: "Encargado de Inventario", OPERATOR: "Trabajador Operativo" };
const roleOptions = Object.entries(roleLabels) as [Role, string][];
type FormData = { fullName: string; email: string; password: string; role: Role };
const emptyForm: FormData = { fullName: "", email: "", password: "", role: "ADMINISTRATIVE" };

export function UsersView() {
  const [data, setData] = useState<Paginated<AppUser> | null>(null); const [search, setSearch] = useState(""); const [role, setRole] = useState(""); const [active, setActive] = useState(""); const [error, setError] = useState(""); const [form, setForm] = useState<FormData>(emptyForm); const [editing, setEditing] = useState<AppUser | null>(null); const [showForm, setShowForm] = useState(false); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { const query = new URLSearchParams({ limit: "20" }); if (search) query.set("search", search); if (role) query.set("role", role); if (active) query.set("active", active); setData(await apiRequest<Paginated<AppUser>>(`/api/admin/users?${query}`)); } catch (caught) { setError((caught as Error).message); } }, [search, role, active]);
  useEffect(() => { void load(); }, [load]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { if (editing) await apiRequest(`/api/admin/users/${editing.id}`, { method: "PATCH", body: JSON.stringify({ fullName: form.fullName, role: form.role }) }); else await apiRequest("/api/admin/users", { method: "POST", body: JSON.stringify(form) }); setShowForm(false); setEditing(null); setForm(emptyForm); await load(); } catch (caught) { setError((caught as Error).message); } finally { setSaving(false); } };
  const changeStatus = async (user: AppUser) => { if (!confirm(`${user.isActive ? "Inactivar" : "Activar"} a ${user.fullName}?`)) return; try { await apiRequest(`/api/admin/users/${user.id}/status`, { method: "PATCH", body: JSON.stringify({ isActive: !user.isActive }) }); await load(); } catch (caught) { setError((caught as Error).message); } };
  const edit = (user: AppUser) => { setEditing(user); setForm({ fullName: user.fullName, email: user.email, password: "", role: user.role }); setShowForm(true); };
  return <div className="mx-auto max-w-[1440px]"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-[28px] font-bold">Lista de usuarios</h2><p className="mt-1 text-sm text-slate-600">Administre las cuentas, roles y estados de acceso de los usuarios del sistema.</p></div><button className="stitch-button stitch-button-primary" onClick={() => { setEditing(null); setForm(emptyForm); setShowForm(true); }}><Icon name="add" />Nuevo usuario</button></div>
    {error && <p role="alert" className="mb-4 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    <form onSubmit={(event) => { event.preventDefault(); void load(); }} className="stitch-card mb-6 grid gap-4 p-4 md:grid-cols-[1fr_200px_180px_auto] md:items-end"><Field label="Buscar por nombre o correo"><input className="stitch-input" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Ej. Luis Gómez..." /></Field><Field label="Rol"><select className="stitch-input" value={role} onChange={(event) => setRole(event.target.value)}><option value="">Todos los roles</option>{roleOptions.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></Field><Field label="Estado"><select className="stitch-input" value={active} onChange={(event) => setActive(event.target.value)}><option value="">Todos los estados</option><option value="true">Activo</option><option value="false">Inactivo</option></select></Field><button className="stitch-button stitch-button-secondary" type="button" onClick={() => { setSearch(""); setRole(""); setActive(""); }}><Icon name="filter" />Limpiar</button></form>
    <div className="stitch-card overflow-hidden"><div className="overflow-x-auto"><table className="stitch-table"><thead><tr><th>Nombre</th><th>Correo</th><th>Rol</th><th>Estado</th><th>Fecha de registro</th><th className="text-right">Acciones</th></tr></thead><tbody>{data?.items.map((user) => <tr key={user.id}><td className="font-medium">{user.fullName}</td><td className="text-slate-600">{user.email}</td><td>{roleLabels[user.role]}</td><td><StatusBadge active={user.isActive} /></td><td className="text-slate-600">{formatDate(user.createdAt)}</td><td><div className="flex justify-end gap-2"><button aria-label={`Editar ${user.fullName}`} onClick={() => edit(user)} className="rounded p-1.5 text-slate-500 hover:bg-slate-100 hover:text-blue-700"><Icon name="edit" /></button><button aria-label={`${user.isActive ? "Inactivar" : "Activar"} ${user.fullName}`} onClick={() => void changeStatus(user)} className="rounded p-1.5 text-slate-500 hover:bg-slate-100 hover:text-blue-700"><Icon name={user.isActive ? "person_off" : "person_check"} /></button></div></td></tr>)}{data && !data.items.length && <tr><td className="p-10 text-center text-slate-500" colSpan={6}>No hay usuarios que coincidan con los filtros.</td></tr>}</tbody></table></div><div className="flex justify-between border-t border-slate-300 px-4 py-3 text-sm text-slate-600"><span>Mostrando {data?.items.length ?? 0} de {data?.total ?? 0} usuarios</span></div></div>
    {showForm && <UserDialog form={form} setForm={setForm} editing={editing} saving={saving} onClose={() => setShowForm(false)} onSubmit={submit} />}
  </div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-medium text-slate-600"><span className="mb-1.5 block">{label}</span>{children}</label>; }
function UserDialog({ form, setForm, editing, saving, onClose, onSubmit }: { form: FormData; setForm: (value: FormData) => void; editing: AppUser | null; saving: boolean; onClose: () => void; onSubmit: (event: FormEvent) => void }) { const set = (key: keyof FormData, value: string) => setForm({ ...form, [key]: value }); return <div className="fixed inset-0 z-30 flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={onSubmit} className="stitch-card w-full max-w-lg p-6"><div className="flex items-start justify-between"><div><h3 className="text-xl font-bold">{editing ? "Editar usuario" : "Nuevo usuario"}</h3><p className="mt-1 text-sm text-slate-500">{editing ? "Actualiza el nombre y rol de acceso." : "La cuenta se creará en Supabase Auth."}</p></div><button type="button" aria-label="Cerrar" onClick={onClose} className="text-slate-500"><Icon name="close" /></button></div><div className="mt-5 grid gap-4"><Field label="Nombre completo"><input required className="stitch-input" value={form.fullName} onChange={(event) => set("fullName", event.target.value)} /></Field><Field label="Correo electrónico"><input required disabled={!!editing} className="stitch-input disabled:bg-slate-100" type="email" value={form.email} onChange={(event) => set("email", event.target.value)} /></Field>{!editing && <Field label="Contraseña temporal"><input required minLength={8} className="stitch-input" type="password" value={form.password} onChange={(event) => set("password", event.target.value)} /></Field>}<Field label="Rol"><select className="stitch-input" value={form.role} onChange={(event) => set("role", event.target.value)}>{roleOptions.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></Field></div><div className="mt-6 flex justify-end gap-2"><button type="button" className="stitch-button stitch-button-secondary" onClick={onClose}>Cancelar</button><button disabled={saving} className="stitch-button stitch-button-primary">{saving ? "Guardando..." : editing ? "Guardar cambios" : "Crear usuario"}</button></div></form></div>; }
const formatDate = (value: string) => new Intl.DateTimeFormat("es-GT", { dateStyle: "short" }).format(new Date(value));
